### ISSUE TITLE
Naming is completely chaotic

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/libhermit-rs#11]
Now the names for this project include:

* HermitCore-rs
* RustyHermit
* libhermit-rs

Same for the hypervisor:
* uhyve
* hermit-caves

This should be unified as long as it is still possible...

**Comment by stlankes** [comment]
Yes, I am working on it

**Comment by stlankes** [comment]
@spickartz @jbreitbart Maybe we should use following name convention:

HermitCore <=> libhermit
HermitCore-rs <=> C/C++ support on top of the Rust-based kernel
RustyHermit <=> for pure Rust applications on top of the Rust kernel

What do you think?

**Comment by jbreitbart** [comment]
I am not sure if I understand the difference between HermitCore-rs and RustyHermit. Shouldn't the kernel have a name? It is the same kernel for both, isn't it?

**Comment by jounathaen** [comment]
> HermitCore-rs <=> C/C++ support on top of the Rust-based kernel
> RustyHermit <=> for pure Rust applications on top of the Rust kernel

Is there a big difference from a user perspective between these? Should these be distinguished at all?

**Comment by stlankes** [comment]
We had an offline discussion and I forgot to update this issue. Only the kernels have names. HermitCore is the C-based kernel (libhermit) and RustyHermit is the Rust-version. All other repositories don't have special name. They consists of examples (e.g. hermit-playground) and utilities (e.g. gcc). In the future, we use the name uhyve for the Rust-based hypervisor. The C version will become obsolete.

What do you think? A better naming convention?

**Comment by jounathaen** [comment]
Sounds good to me :+1: 

To avoid confusion, I'd suggest to remove the name _libhermit(-rs)_ wherever possible.
However, I think it's to late for a change of the url... 😔

**Comment by stlankes** [comment]
I agree!
