### ISSUE TITLE
Intructions for local build

### ISSUE THREAD

**Issue by mincheolsung** [hermitcore/libhermit-rs#13]
Hi!

I am trying to locally build RustyHermit.
Are there instructions for that? 
I tried "make" but failed to build.

mincheol@mir3:~/libhermit-rs$ make
Build libhermit
    Finished dev [optimized + debuginfo] target(s) in 0.02s
make arch=x86_64 release=0 -C tests
make[1]: Entering directory '/home/mincheol/libhermit-rs/tests'
   Compiling nodrop v0.1.13
   Compiling lazy_static v1.4.0
   Compiling cfg-if v0.1.9
   Compiling scopeguard v1.0.0
   Compiling fnv v1.0.6
   Compiling either v1.5.2
   Compiling itoa v0.4.4
   Compiling libc v0.2.62
   Compiling byteorder v1.3.2
   Compiling memoffset v0.5.1
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `cfg-if`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: aborting due to previous error

error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

For more information about this error, try `rustc --explain E0463`.
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `nodrop`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `either`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

error: aborting due to previous error

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
For more information about this error, try `rustc --explain E0463`.
error: Could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `lazy_static`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `scopeguard`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `memoffset`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

error: Could not compile `fnv`.
warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `itoa`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-hermit` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `byteorder`.

To learn more, run the command again with --verbose.
Makefile:23: recipe for target 'default' failed
make[1]: *** [default] Error 101
make[1]: Leaving directory '/home/mincheol/libhermit-rs/tests'
Makefile:23: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by stlankes** [comment]
Excuse me, you are right. A documentation is missing to build the Rust compiler independent from the Docker container.

In principle, you need the Rust toolchain with our extensions. You find our version at https://github.com/hermitcore/rust. Please checkout the current version and switch to the branch `hermit`:

> git clone git@github.com:hermitcore/rust.git
> cd rust
> git checkout hermit

To build the toolchain, you need the configuration file `config.toml` in the root directory of the repository. A template `config.toml.example` is part of the repository. However, I would start with my [version](https://git.rwth-aachen.de/acs/public/hermitcore/hermit-docker/blob/master/config.toml), which already enable the support of RustHermit. You have only to change the installation path (see variable `prefix` in `config.toml`).

Afterwards you are able to build the toolchain with following command `./x.py install`. This will take a while. I would expect at least 45 minutes. Afterwards you have to set the environment variable `XARGO_RUST_SRC` to `/installation_path/lib/rustlib/src/rust/src/`. Please replace `installation_path` to the location, where you install the toolchain.

Afterwards, the makefile should in the `libhermit-rs` repository should work. :-)

The docker container contains a prebuild version. You could also use this version to build our [examples](https://git.rwth-aachen.de/acs/public/hermitcore/libhermit-rs/-/jobs/447473).

**Comment by mincheolsung** [comment]
Thanks!
However, I got some linking issues when I did "make" on libhermit-rs.
The linker can't find sys_netread(), sys_netwrite(), sys_network_init(), and sys_is_polling().
I tried to find where those functions are defined, but I can't find them.
Can you give me tips?

**Comment by stlankes** [comment]
Please, pull the repository. I think that you aren’t working on the latest version of libhermit-rs.

**Comment by mincheolsung** [comment]
Thanks! I can now play with the test application (hctests).
