### ISSUE TITLE
Add syscalls to Rust libstd

### ISSUE THREAD

**Issue by mincheolsung** [hermitcore/libhermit-rs#14]
Hi, there is no "issues section" on the hermitcore:rust repo, so I post here.
I am now trying to add some system calls on RustyHermit.
I created my_syscalls.rs on rust/src/libstd/sys/hermit/ and tried to import it from the libhermit-rs/tests/src/tests/mod.rs.

As I observed, I can't directly use it because the libstd/sys is private.
So do I need to create interfaces for my system calls and overwrite them on rust/src/libstd/sys/hermit/my_syscalls.rs?

**Comment by stlankes** [comment]
Why do you close it? Do you understand, how you could a new syscall?

**Comment by mincheolsung** [comment]
Hi, 
I was trying to test kernel features which I added to RustyHermit.
But I figured out that I was able to test them without new system calls.
I am not sure whether I eventually need the new system calls.

**Comment by stlankes** [comment]
Currently, I export functions from the kernel as C function. For instance, https://github.com/hermitcore/libhermit-rs/blob/master/src/syscalls/tasks.rs#L154 is the interface to trigger the scheduler. I would add a system call in this directory.
