### ISSUE TITLE
Improve randomness syscalls

### ISSUE THREAD

**Issue by newpavlov** [hermitcore/libhermit-rs#143]
The RDRAND code used in `generate_random_number32/64` does not contain a workaround for the AMD glitch. You can take a look at the [`getrandom` code](https://github.com/rust-random/getrandom/blob/master/src/rdrand.rs#L30-L46) for reference.

Also it would be nice if instead of `generate_random_number32/64` you will expose a Linux-like interface, i.e. a syscall which will work on buffers.

**Comment by stlankes** [comment]
Thanks for the suggestions! I will work on it.
