### ISSUE TITLE
libhermit-rs fails to compile without feature "pci"

### ISSUE THREAD

**Issue by jschwe** [hermitcore/libhermit-rs#157]
`drivers/net` contains imports / uses functions that depend on `pci` being enabled.

```
 error[E0433]: failed to resolve: use of undeclared crate or module `pci`
     --> src/drivers/net/mod.rs:149:30
      |
  149 |     let check_scheduler = match pci::get_network_driver() {
      |                                 ^^^ use of undeclared crate or module `pci`

```
I'm not really familiar with the network module, but if it depends on pci, it should be disabled if pci is not enabled. Alternatively we could remove the `pci` feature  and simply unconditionally enable it.

**Comment by stlankes** [comment]
We fixed it with #160
