### ISSUE TITLE
detection of virtio devices within RustyHermit

### ISSUE THREAD

**Issue by stlankes** [hermitcore/libhermit-rs#17]
It is possible to run RustyHermit within qemu. For instance, the following starts the test application within qemu:

> qemu-system-x86_64 -display none -smp 1 -m 64M -serial stdio  -kernel loader/target/x86_64-unknown-hermit-loader/debug/hermit-loader -initrd tests/target/x86_64-unknown-hermit/debug/rusty_tests -cpu qemu64,apic,fsgsbase,pku,rdtscp,xsave,fxsr

Hereby, `hermit_loader` is a basic loader to initialize the system.

In the C version is already a basic virtio support available. This [code snippet](https://github.com/hermitcore/libhermit/blob/master/drivers/net/vioif.c#L331-L336) detects a virtio device and can be used as template for RustyHermit. Consequently, we have to use [qemu with virtio support](https://www.linux-kvm.org/page/Virtio) and modify RustyHermit to detect such a device.

**Comment by RealRichardParker** [comment]
We've begun work on this issue, and am wondering if we are on the right track. We have added the following function to src/drivers/net/uhyve.rs

```
fn detect_virtio_device() -> Option<pci::PciAdapter> {
	for i in 0x100..0x103F {
		let adapter = pci::get_adapter(0x1AF4, i);
		match adapter {
			Some(value) => return adapter,
			None => {},
		}
	}
	None
}
```

**Comment by stlankes** [comment]
hm, is on Uhyve the PCI interface initialized? I would start with qemu. It should scan the PCI address space

**Comment by MatthewHinton56** [comment]
The latest pull request solved this issue, can we go ahead and close this issue?

**Comment by stlankes** [comment]
Help me, I thought that I merged all PR...

**Comment by MatthewHinton56** [comment]
This is still marked as an active issue, even though the PR was merged. I do not have close permissions for the issue itself.

**Comment by stlankes** [comment]
Sorry, I was blind.
