### ISSUE TITLE
File mode passed to uhyve is given in hex instead of octal.

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/libhermit-rs#191]
The `mode` in the `open` hypercall is passed in hex, but it should be passed as octal. This results in strange permissions of files which are created by uhyve.

https://github.com/hermitcore/libhermit-rs/blob/44eaa9f693566413884f505552f74f2e25863e78/src/syscalls/interfaces/mod.rs#L58-L69

Example: `1991 = 0x777` is passed but it should be `511 = 0o777` instead. The `flags` field  is passed correctly.

@tlambertz pointed out that this has to be fixed in the stdlib

**Comment by mkroening** [comment]
Fixed by https://github.com/rust-lang/rust/pull/109368.
