### ISSUE TITLE
License type in Github API is set to "Other"

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/libhermit-rs#255]
Probably due to the dual licensing. However, having one of the two licenses here might help with automated license tools or simmilar.

**Comment by mkroening** [comment]
Having one of those two might be misleading, wouldn't it? Also, clicking on `View License` takes you to the Apache license currently.

Looking at the [rust repository](https://github.com/rust-lang/rust) or popular crates, that's the same situation there.

**Comment by jounathaen** [comment]
Yeah, actually it doesn't matter to much. If this becomes a real problem, we'll re-open this.
