### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by ColinFinck** [hermitcore/libhermit-rs#291]
The Slack link at the bottom of README.md leads to https://radiant-ridge-95061.herokuapp.com/, which doesn't exist (anymore?)

**Comment by stlankes** [comment]
Hello Colin, you are right. But we updated the link in the README. Do you read an old version?

**Comment by mkroening** [comment]
https://github.com/hermitcore/libhermit-rs/commit/abe451090c99ef1bca72a613c88057ae81a1b487 updated the link of the slack badge but not the link at the bottom of the README ([Contribution](https://github.com/hermitcore/libhermit-rs/blob/87f8f73a7bf630ab16509d4aa3b94e5fd14a0085/README.md#contribution)).

I created these PRs to fix the issue:

* https://github.com/hermitcore/libhermit-rs/pull/295
* https://github.com/hermitcore/rusty-hermit/pull/173
