### ISSUE TITLE
Tokenizer: Code Confusing and Error Handling Broken

### ISSUE THREAD

**Issue by lrapp-x41-pub** [hermitcore/libhermit-rs#346]
The tokenizer code in [src/util.rs](https://github.com/hermitcore/libhermit-rs/blob/master/src/util.rs) is confusing and the error handling is broken.
1. Confusing code:
When a quote sign (`"` or `'`) appears in the input, the `unquote` function is called. The current char (which is the quote sign) and the input are passed to the `unquote` function. https://github.com/hermitcore/libhermit-rs/blob/f5408c23771eb37f0be57986db19ca9d0d290cf7/src/util.rs#L21-L23
The first parameter passed to the `unquote` function is called `delimiter`, which is very confusing as it is not the delimiter used to split the string at, but the quote sign.
https://github.com/hermitcore/libhermit-rs/blob/f5408c23771eb37f0be57986db19ca9d0d290cf7/src/util.rs#L44-L46
Also, line 55 and 56 are redundant to line 61.

2. Broken error handling:
When an invalid escape char occurs inside the quoted part, the `unquote` function immediately returns an error and the `tokenize` function does ignore the part between (and including) the quote begin and the invalid escape char, thus this part gets dropped. 
 https://github.com/hermitcore/libhermit-rs/blob/f5408c23771eb37f0be57986db19ca9d0d290cf7/src/util.rs#L62
 E.g. `foo "bar\z"` is tokenized as `["foo"]`.
 As an additional effect, the quoted area is now "flipped". The `tokenize` function continues to parse the input at the point where the `unquote` function returned the error (which is inside the quoted area). It splits at the delimiter, but should not do this. When the `tokenize` function reaches the quote end sign, it interprets it as a quote begin sign and calls the unquote function again.
 The unquote function will run into an error, as there is no end quote and show the same behavior as described above: Everything between the last (un)quote char and the end of the string will be dropped.
 https://github.com/hermitcore/libhermit-rs/blob/f5408c23771eb37f0be57986db19ca9d0d290cf7/src/util.rs#L73
E.g. `foo "bar\z baz biz" nope ` is tokenized as `["foo", "baz", "biz"]`

**Comment by mkroening** [comment]
I think it would be best to outsource this logic to a crate. I opened https://github.com/tmiasko/shell-words/issues/8.
