### ISSUE TITLE
Migrate `PriorityTaskQueue` to use `std`'s `LinkedList`

### ISSUE THREAD

**Issue by mkroening** [hermitcore/libhermit-rs#377]
Self-made linked lists are notoriously difficult in Rust.

**Comment by michaelRichards99** [comment]
I am a student from the Virtualization class at the University of Texas at Austin, and participating open source development is part of the course requirement. We are willing to fix this if y'all want. Thanks!

**Comment by mkroening** [comment]
Sure, if you want to have a try at this, go for it!

It might not be very straight forward, because the previous and next tasks in the list are baked into the `Task` struct. I am not sure, if it entirely makes sense to do this at all, but that would require some evaluation and exploration to find out.
