### ISSUE TITLE
Ensure that the latest commit on master / devel branch works

### ISSUE THREAD

**Issue by jschwe** [hermitcore/libhermit-rs#46]
In order to ensure that the master / devel branches are always in a working state I propose the following changes:

1. [Protect master and possibly devel](https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions) (in rusty-hermit) and disallow direct pushes to these branches. 

2. These branches should only be changed via MRs or PRs and [only if the pipeline succeeds](https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks). This should be enforced via github settings. 

3. Improve the pipeline in libhermit-rs so that the demo tests are actually executed. Currently the situation is such, that the pipeline in libhermit-rs often succeeds, since it only checks if the code builds, even though there are still errors, which become evident when the changes get integrated into the rusty-hermit repository. PR #40 should help with that.
4. Change the pipeline so that it runs for pushes on every branch. If costs are an issue, then maybe the matrix could be reduced for pushes. This encourages working on feature branches and gives direct feedback to the developer, without the need to open a PR or push to master.
5. Encourage the use of `git rebase -i` on branches before merging into master to keep the History clean and squash commits like `minor changes to pass the format check` together with the commit it originally belonged to.

**Comment by stlankes** [comment]
I know, my working style isn't great. You are right, I have to change it. I will protect the branch.

**Comment by jounathaen** [comment]
If you want to see some DevOps Nightmares, take a look at the RustyHermit git graph: https://github.com/hermitcore/rusty-hermit/network 

I wonder how @stlankes suceeded to work with two complete separate branches `master` and `devel` :stuck_out_tongue_winking_eye:

**Comment by stlankes** [comment]
Hehe, I have to `devel` at least in lib libhermit-rs. It is their for historical reasons.
