### ISSUE TITLE
Fix network specification via QEMU command line

### ISSUE THREAD

**Issue by mkroening** [hermitcore/libhermit-rs#522]
https://github.com/hermitcore/libhermit-rs/commit/eb2a46fe4d2892957a7e31fd8ce60bcd21a78f52 broke https://github.com/hermitcore/libhermit-rs/pull/337.

CC: @stlankes

**Comment by stlankes** [comment]
Help me, what doesn't work?

**Comment by mkroening** [comment]
https://github.com/hermitcore/libhermit-rs/pull/337 parses QEMU args and puts the values into environment variables of the application. This was received before via `std::env::var` in `hermit-sys`. Now the env vars are required at compile time, so the values from QEMU's command line don't end up anywhere.

This is not a problem that I have experienced but this currently breaks `runh`, if I am not mistaken. We could either:
* Make runh recompile the kernel each time with the corresponding values.
or
* Let `libhermit-rs::env` not put the parsed values into the app's environment but deliver them to `libhermit-rs::net` directly.
