### ISSUE TITLE
Remove internal `shutdown` function

### ISSUE THREAD

**Issue by mkroening** [hermitcore/libhermit-rs#670]
This has been introduced because of improper initialization of `SYS`, which has since been fixed.

**Comment by richiewahidin** [comment]
Hi. I am a student in UT Austin, and I am interested in working on this issue for my Virtualization project. Can you assign this issue to me?

**Comment by mkroening** [comment]
Sure!

For reference:
- https://github.com/hermitcore/libhermit-rs/pull/384
- https://github.com/hermitcore/libhermit-rs/pull/600

**Comment by mkroening** [comment]
Fixed by https://github.com/hermitcore/libhermit-rs/pull/695.
