### ISSUE TITLE
Don't use syscalls internally

### ISSUE THREAD

**Issue by mkroening** [hermitcore/libhermit-rs#676]
For example, `crate::__sys_malloc` should be replaced by appropriate calls to the `alloc` crate.

https://github.com/hermitcore/libhermit-rs/blob/2203b5ae3dfc247c34098003c47ea1af2613cb66/src/syscalls/interfaces/uhyve.rs#L145

**Comment by nathanwhyte** [comment]
Hi Martin,

I'm taking a Virtualization course at UT Austin and we've been asked to contribute to open-source virtualization repositories for one of our projects. Could I take a shot at resolving this issue?

**Comment by mkroening** [comment]
Sure, go ahead! :)
