### ISSUE TITLE
Can't boot kernels on Uhyve in non-release mode

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/libhermit-rs#756]
When running a kernel in non-release mode on uhyve, the Kernel hangs forever, as there is a bug in the APIC code that is not triggered in release mode:
```
[0][PANIC] panicked at 'attempt to add with overflow', src/arch/x86_64/kernel/apic.rs:515:21
[0][INFO] Number of interrupts
```
This is already fixed in https://github.com/hermitcore/libhermit-rs/commit/32510fd599ad3328e85d8c3d5ff7b36f4536c0a6, but not yet released.

**Comment by mkroening** [comment]
This is released now and succeeds in [CI](https://github.com/hermitcore/rusty-hermit/actions/runs/5334482604/jobs/9666315276).
