### ISSUE TITLE
Compiling fails with segfault

### ISSUE THREAD

**Issue by jschwe** [hermitcore/libhermit-rs#94]
Compiling libhermit-rs currently fails with a segmentation fault. This behaviour was introduced with the `nightly-2020-08-24`. This is likely to be related to the following issue: https://github.com/rust-lang/rust/issues/75922. 
The comments there suggest that we will have to make changes on our end to the `#[naked]` functions.

**Comment by stlankes** [comment]
Yes! Hm, I also create an issue rust-lang/rust#76061. I will look into rust-lang/rust#75922.

**Comment by tlambertz** [comment]
I had a similar issue with naked functions recently (though this were runtime issues), where naked functions with parameters behaved weirdly. https://github.com/rust-lang/rust/pull/75417 fixed some of that, but people are unsure if naked+parameters should be supported or not. My workaround was using `global_asm!` and declaring the symbol as a `extern 'C' fn`.

**Comment by stlankes** [comment]
Yes, seems to be the better solution

**Comment by stlankes** [comment]
I close this issue. PR #95 solved it.
